import { SurahMeta } from './types';

export const ALL_SURAHS: SurahMeta[] = [
  { number: 1, name: "Al-Fatihah", englishName: "The Opening", verseCount: 7, meaning: "Pembukaan" },
  { number: 2, name: "Al-Baqarah", englishName: "The Cow", verseCount: 286, meaning: "Sapi Betina" },
  { number: 3, name: "Ali 'Imran", englishName: "Family of Imran", verseCount: 200, meaning: "Keluarga Imran" },
  { number: 4, name: "An-Nisa'", englishName: "The Women", verseCount: 176, meaning: "Wanita" },
  { number: 5, name: "Al-Ma'idah", englishName: "The Table Spread", verseCount: 120, meaning: "Hidangan" },
  { number: 6, name: "Al-An'am", englishName: "The Cattle", verseCount: 165, meaning: "Binatang Ternak" },
  { number: 7, name: "Al-A'raf", englishName: "The Heights", verseCount: 206, meaning: "Tempat Tertinggi" },
  { number: 8, name: "Al-Anfal", englishName: "The Spoils of War", verseCount: 75, meaning: "Harta Rampasan Perang" },
  { number: 9, name: "At-Tawbah", englishName: "The Repentance", verseCount: 129, meaning: "Pengampunan" },
  { number: 10, name: "Yunus", englishName: "Jonah", verseCount: 109, meaning: "Yunus" },
  { number: 11, name: "Hud", englishName: "Hud", verseCount: 123, meaning: "Hud" },
  { number: 12, name: "Yusuf", englishName: "Joseph", verseCount: 111, meaning: "Yusuf" },
  { number: 13, name: "Ar-Ra'd", englishName: "The Thunder", verseCount: 43, meaning: "Guruh" },
  { number: 14, name: "Ibrahim", englishName: "Abraham", verseCount: 52, meaning: "Ibrahim" },
  { number: 15, name: "Al-Hijr", englishName: "The Rocky Tract", verseCount: 99, meaning: "Bukit Batu" },
  { number: 16, name: "An-Nahl", englishName: "The Bee", verseCount: 128, meaning: "Lebah" },
  { number: 17, name: "Al-Isra'", englishName: "The Night Journey", verseCount: 111, meaning: "Perjalanan Malam" },
  { number: 18, name: "Al-Kahf", englishName: "The Cave", verseCount: 110, meaning: "Gua" },
  { number: 19, name: "Maryam", englishName: "Mary", verseCount: 98, meaning: "Maryam" },
  { number: 20, name: "Ta-Ha", englishName: "Ta-Ha", verseCount: 135, meaning: "Ta Ha" },
  { number: 21, name: "Al-Anbiya'", englishName: "The Prophets", verseCount: 112, meaning: "Nabi-Nabi" },
  { number: 22, name: "Al-Hajj", englishName: "The Pilgrimage", verseCount: 78, meaning: "Haji" },
  { number: 23, name: "Al-Mu'minun", englishName: "The Believers", verseCount: 118, meaning: "Orang-orang Mukmin" },
  { number: 24, name: "An-Nur", englishName: "The Light", verseCount: 64, meaning: "Cahaya" },
  { number: 25, name: "Al-Furqan", englishName: "The Criterion", verseCount: 77, meaning: "Pembeda" },
  { number: 26, name: "Ash-Shu'ara'", englishName: "The Poets", verseCount: 227, meaning: "Penyair" },
  { number: 27, name: "An-Naml", englishName: "The Ant", verseCount: 93, meaning: "Semut" },
  { number: 28, name: "Al-Qasas", englishName: "The Stories", verseCount: 88, meaning: "Kisah-kisah" },
  { number: 29, name: "Al-Ankabut", englishName: "The Spider", verseCount: 69, meaning: "Laba-laba" },
  { number: 30, name: "Ar-Rum", englishName: "The Romans", verseCount: 60, meaning: "Bangsa Romawi" },
  { number: 31, name: "Luqman", englishName: "Luqman", verseCount: 34, meaning: "Luqman" },
  { number: 32, name: "As-Sajdah", englishName: "The Prostration", verseCount: 30, meaning: "Sujud" },
  { number: 33, name: "Al-Ahzab", englishName: "The Combined Forces", verseCount: 73, meaning: "Golongan yang Bersekutu" },
  { number: 34, name: "Saba'", englishName: "Sheba", verseCount: 54, meaning: "Saba'" },
  { number: 35, name: "Fatir", englishName: "Originator", verseCount: 45, meaning: "Pencipta" },
  { number: 36, name: "Ya-Sin", englishName: "Ya Sin", verseCount: 83, meaning: "Ya Sin" },
  { number: 37, name: "As-Saffat", englishName: "Those Who Set The Ranks", verseCount: 182, meaning: "Barisan-barisan" },
  { number: 38, name: "Sad", englishName: "The Letter 'Saad'", verseCount: 88, meaning: "Shaad" },
  { number: 39, name: "Az-Zumar", englishName: "The Troops", verseCount: 75, meaning: "Rombongan-rombongan" },
  { number: 40, name: "Ghafir", englishName: "The Forgiver", verseCount: 85, meaning: "Yang Mengampuni" },
  { number: 41, name: "Fussilat", englishName: "Explained in Detail", verseCount: 54, meaning: "Yang Dijelaskan" },
  { number: 42, name: "Ash-Shura", englishName: "The Consultation", verseCount: 53, meaning: "Musyawarah" },
  { number: 43, name: "Az-Zukhruf", englishName: "The Ornaments of Gold", verseCount: 89, meaning: "Perhiasan" },
  { number: 44, name: "Ad-Dukhan", englishName: "The Smoke", verseCount: 59, meaning: "Kabut" },
  { number: 45, name: "Al-Jathiyah", englishName: "The Crouching", verseCount: 37, meaning: "Yang Berlutut" },
  { number: 46, name: "Al-Ahqaf", englishName: "The Wind-Curved Sandhills", verseCount: 35, meaning: "Bukit-bukit Pasir" },
  { number: 47, name: "Muhammad", englishName: "Muhammad", verseCount: 38, meaning: "Muhammad" },
  { number: 48, name: "Al-Fath", englishName: "The Victory", verseCount: 29, meaning: "Kemenangan" },
  { number: 49, name: "Al-Hujurat", englishName: "The Rooms", verseCount: 18, meaning: "Kamar-kamar" },
  { number: 50, name: "Qaf", englishName: "The Letter 'Qaf'", verseCount: 45, meaning: "Qaf" },
  { number: 51, name: "Adh-Dhariyat", englishName: "The Winnowing Winds", verseCount: 60, meaning: "Angin yang Menerbangkan" },
  { number: 52, name: "At-Tur", englishName: "The Mount", verseCount: 49, meaning: "Bukit" },
  { number: 53, name: "An-Najm", englishName: "The Star", verseCount: 62, meaning: "Bintang" },
  { number: 54, name: "Al-Qamar", englishName: "The Moon", verseCount: 55, meaning: "Bulan" },
  { number: 55, name: "Ar-Rahman", englishName: "The Beneficent", verseCount: 78, meaning: "Yang Maha Pemurah" },
  { number: 56, name: "Al-Waqi'ah", englishName: "The Inevitable", verseCount: 96, meaning: "Hari Kiamat" },
  { number: 57, name: "Al-Hadid", englishName: "The Iron", verseCount: 29, meaning: "Besi" },
  { number: 58, name: "Al-Mujadila", englishName: "The Pleading Woman", verseCount: 22, meaning: "Wanita yang Menggugat" },
  { number: 59, name: "Al-Hashr", englishName: "The Exile", verseCount: 24, meaning: "Pengusiran" },
  { number: 60, name: "Al-Mumtahanah", englishName: "She That Is To Be Examined", verseCount: 13, meaning: "Wanita yang Diuji" },
  { number: 61, name: "As-Saff", englishName: "The Ranks", verseCount: 14, meaning: "Barisan" },
  { number: 62, name: "Al-Jumu'ah", englishName: "The Congregation, Friday", verseCount: 11, meaning: "Hari Jum'at" },
  { number: 63, name: "Al-Munafiqun", englishName: "The Hypocrites", verseCount: 11, meaning: "Orang-orang Munafik" },
  { number: 64, name: "At-Taghabun", englishName: "The Mutual Disillusion", verseCount: 18, meaning: "Hari Dinampakkan Kesalahan" },
  { number: 65, name: "At-Talaq", englishName: "The Divorce", verseCount: 12, meaning: "Talak" },
  { number: 66, name: "At-Tahrim", englishName: "The Prohibition", verseCount: 12, meaning: "Mengharamkan" },
  { number: 67, name: "Al-Mulk", englishName: "The Sovereignty", verseCount: 30, meaning: "Kerajaan" },
  { number: 68, name: "Al-Qalam", englishName: "The Pen", verseCount: 52, meaning: "Pena" },
  { number: 69, name: "Al-Haqqah", englishName: "The Reality", verseCount: 52, meaning: "Hari Kiamat" },
  { number: 70, name: "Al-Ma'arij", englishName: "The Ascending Stairways", verseCount: 44, meaning: "Tempat Naik" },
  { number: 71, name: "Nuh", englishName: "Noah", verseCount: 28, meaning: "Nuh" },
  { number: 72, name: "Al-Jinn", englishName: "The Jinn", verseCount: 28, meaning: "Jin" },
  { number: 73, name: "Al-Muzzammil", englishName: "The Enshrouded One", verseCount: 20, meaning: "Orang yang Berselimut" },
  { number: 74, name: "Al-Muddaththir", englishName: "The Cloaked One", verseCount: 56, meaning: "Orang yang Berkemul" },
  { number: 75, name: "Al-Qiyamah", englishName: "The Resurrection", verseCount: 40, meaning: "Hari Kiamat" },
  { number: 76, name: "Al-Insan", englishName: "The Man", verseCount: 31, meaning: "Manusia" },
  { number: 77, name: "Al-Mursalat", englishName: "The Emissaries", verseCount: 50, meaning: "Malaikat-malaikat yang Diutus" },
  { number: 78, name: "An-Naba", englishName: "The Tidings", verseCount: 40, meaning: "Berita Besar" },
  { number: 79, name: "An-Nazi'at", englishName: "Those Who Drag Forth", verseCount: 46, meaning: "Malaikat Pencabut" },
  { number: 80, name: "Abasa", englishName: "He Frowned", verseCount: 42, meaning: "Ia Bermuka Masam" },
  { number: 81, name: "At-Takwir", englishName: "The Overthrowing", verseCount: 29, meaning: "Menggulung" },
  { number: 82, name: "Al-Infitar", englishName: "The Cleaving", verseCount: 19, meaning: "Terbelah" },
  { number: 83, name: "Al-Mutaffifin", englishName: "The Defrauding", verseCount: 36, meaning: "Orang-orang Curang" },
  { number: 84, name: "Al-Inshiqaq", englishName: "The Sundering", verseCount: 25, meaning: "Terbelah" },
  { number: 85, name: "Al-Buruj", englishName: "The Mansions of the Stars", verseCount: 22, meaning: "Gugusan Bintang" },
  { number: 86, name: "At-Tariq", englishName: "The Morning Star", verseCount: 17, meaning: "Yang Datang di Malam Hari" },
  { number: 87, name: "Al-A'la", englishName: "The Most High", verseCount: 19, meaning: "Yang Paling Tinggi" },
  { number: 88, name: "Al-Ghashiyah", englishName: "The Overwhelming", verseCount: 26, meaning: "Hari Pembalasan" },
  { number: 89, name: "Al-Fajr", englishName: "The Dawn", verseCount: 30, meaning: "Fajar" },
  { number: 90, name: "Al-Balad", englishName: "The City", verseCount: 20, meaning: "Negeri" },
  { number: 91, name: "Ash-Shams", englishName: "The Sun", verseCount: 15, meaning: "Matahari" },
  { number: 92, name: "Al-Lail", englishName: "The Night", verseCount: 21, meaning: "Malam" },
  { number: 93, name: "Ad-Duha", englishName: "The Morning Hours", verseCount: 11, meaning: "Waktu Dhuha" },
  { number: 94, name: "Ash-Sharh", englishName: "The Relief", verseCount: 8, meaning: "Melapangkan" },
  { number: 95, name: "At-Tin", englishName: "The Fig", verseCount: 8, meaning: "Buah Tin" },
  { number: 96, name: "Al-Alaq", englishName: "The Clot", verseCount: 19, meaning: "Segumpal Darah" },
  { number: 97, name: "Al-Qadr", englishName: "The Power", verseCount: 5, meaning: "Kemuliaan" },
  { number: 98, name: "Al-Bayyinah", englishName: "The Clear Proof", verseCount: 8, meaning: "Bukti" },
  { number: 99, name: "Az-Zalzalah", englishName: "The Earthquake", verseCount: 8, meaning: "Kegoncangan" },
  { number: 100, name: "Al-Adiyat", englishName: "The Courser", verseCount: 11, meaning: "Kuda Perang" },
  { number: 101, name: "Al-Qari'ah", englishName: "The Calamity", verseCount: 11, meaning: "Hari Kiamat" },
  { number: 102, name: "At-Takathur", englishName: "The Rivalry in World Increase", verseCount: 8, meaning: "Bermegah-megahan" },
  { number: 103, name: "Al-Asr", englishName: "The Declining Day", verseCount: 3, meaning: "Masa" },
  { number: 104, name: "Al-Humazah", englishName: "The Traducer", verseCount: 9, meaning: "Pengumpat" },
  { number: 105, name: "Al-Fil", englishName: "The Elephant", verseCount: 5, meaning: "Gajah" },
  { number: 106, name: "Quraish", englishName: "Quraysh", verseCount: 4, meaning: "Suku Quraisy" },
  { number: 107, name: "Al-Ma'un", englishName: "The Small Kindnesses", verseCount: 7, meaning: "Barang-barang Berguna" },
  { number: 108, name: "Al-Kawthar", englishName: "The Abundance", verseCount: 3, meaning: "Nikmat Berlimpah" },
  { number: 109, name: "Al-Kafirun", englishName: "The Disbelievers", verseCount: 6, meaning: "Orang-orang Kafir" },
  { number: 110, name: "An-Nasr", englishName: "The Succour", verseCount: 3, meaning: "Pertolongan" },
  { number: 111, name: "Al-Masad", englishName: "The Palm Fibre", verseCount: 5, meaning: "Gejolak Api" },
  { number: 112, name: "Al-Ikhlas", englishName: "The Sincerity", verseCount: 4, meaning: "Ikhlas" },
  { number: 113, name: "Al-Falaq", englishName: "The Daybreak", verseCount: 5, meaning: "Waktu Subuh" },
  { number: 114, name: "An-Nas", englishName: "The Mankind", verseCount: 6, meaning: "Manusia" }
];